### ISSUE TITLE
If more then 2 airgradients running, only one sensor provides data in HA

### ISSUE THREAD

**Issue by Impatience71** [ajfriesen/ESPHome-AirGradient#2]
First of all - Thanks for your awsome integration !
When I install 2 airgradients (name is different in the config of course), the ESPHome log shows that both are working, each have different IP addresses, both deliver different values. But in Grafana only one of the sensor provides accessable data. Would it be possible that they collide somehow ? 
Peter

**Comment by ajfriesen** [comment]
Mh, unfortunately I do not have 2 devices to test that.

Could you try to change the name for the sensors and not only the device itself?
Maybe the sensors need different values to be different things in your whatever you are using.

I am guessing influxdb with grafana from the home assistant add ons?

**Comment by sam-harry** [comment]
I have tested with two airgradients: their yaml are identical except the esphome name, air-gradient and air-gradient-1. In my homeassistant and grafana instances they show different sensor values. For example, air-gradient and air-gradient-1 have sensair_co2_value and sensair_co2_value_2, respectively.

**Comment by ajfriesen** [comment]
Mh, if sensors have different names and the entity as well I see no problem why Grafana is not showing you both.

**Comment by bleugray** [comment]
two devices working perfectly for me with only differnces being the names

esphome:
  name: air-gradient-1

esphome:
  name: air-gradient-2

**Comment by ajfriesen** [comment]
Will close this since it seems to work for others.
If you need help regarding this maybe go to the home [assistant forum](https://community.home-assistant.io/c/esphome/36) or the discord for [esphome](https://discord.com/invite/KhAMKrd) and/or [home assistant](https://discord.com/invite/c5DvZ4e).
There are more and more knowledgeable people than just me and the few others which use this project 🙂
